# Change these first
owner: bloxtechgroup # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: BloxTech Dashboard
    url: https://bloxtech.tech/admin
  - name: BloxTech API (Roblox)
    url: https://bloxtech.tech/apiv2/status.php
  - name: RocketApps Dashboard
    url: https://rocketapps.bloxtech.tech
  - name: RocketApps API (Roblox)
    url: https://roblox-rocketapps.bloxtech.tech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  name: BloxTech
  theme: night
  introTitle: "**BloxTech Group** provides hiring resources to accelerate group growth, for free!"
  introMessage: We promise 99% uptime and transparency — decentralised from BloxTech's ecosystem
  navbar:
    - title: Status
      href: /status

i18n:
  footer: "Uptime is updated automatically and can't be modified by BloxTech"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
